CREATE DATABASE IF NOT EXISTS Behisebe;
USE Behisebe;

CREATE TABLE Bank (
	BankID VARCHAR(255) NOT NULL,
	BankName VARCHAR(255) NOT NULL,
	IsDefault TINYINT (1) NOT NULL,
	Notes TEXT,
	PRIMARY KEY (BankID)
);
