CREATE DATABASE IF NOT EXISTS Behisebe;
USE Behisebe;


CREATE TABLE User (
	ID VARCHAR(255) NOT NULL UNIQUE,
	FirstName VARCHAR(255),
	LastName VARCHAR(255),
	Email VARCHAR(255),
	PRIMARY KEY (ID)
);
-- Demo data
INSERT INTO User
(ID,FirstName,LastName,Email)
VALUES
("1234567890","Sagnik","Sarkar","sagniksarkar@ymail.com");

CREATE TABLE BankAccountType (
	ID TINYINT NOT NULL AUTO_INCREMENT UNIQUE,
	AccountType VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);

INSERT INTO BankAccountType
(AccountType)
VALUES 
("Current Account"),
("Savings Account"),
("Salary Account");



CREATE TABLE Bank (
	BankID VARCHAR(255) NOT NULL UNIQUE,
	BankName VARCHAR(255) NOT NULL,
	AccountType TINYINT(3),
	UserID VARCHAR(255),
	IsDefault TINYINT (1) NOT NULL,
	Notes TEXT,
	PRIMARY KEY (BankID),
	FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE,
	FOREIGN KEY (AccountType) REFERENCES BankAccountType(ID) ON DELETE CASCADE
);

-- Expense related statements

CREATE TABLE PartialPaymemnt (
	ID VARCHAR(255) NOT NULL UNIQUE,
	OnDate DATE NOT NULL,
	Amount INT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Person (
	ID VARCHAR(255) NOT NULL UNIQUE,
	Name VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
);

CREATE TABLE Lend (
	ID VARCHAR(255) NOT NULL UNIQUE,
	LendTo VARCHAR(255) NOT NULL,
	OnDate DATE	NOT NULL,
	FullPayment TINYINT(1),
	PartialPayID VARCHAR(255) NULL,
	PaymentOnDate DATE,
	PRIMARY KEY (ID),
	FOREIGN KEY (LendTo) REFERENCES Person (ID) ON DELETE CASCADE,
	Foreign Key (PartialPayID) REFERENCES PartialPaymemnt (ID) ON DELETE CASCADE

);

CREATE TABLE Expense (
	ID VARCHAR(255) NOT NULL UNIQUE,
	BankID VARCHAR(255) NOT NULL,
	UserID VARCHAR(255) NOT NULL,
	LendID VARCHAR(255) NULL,
	Amount INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (BankID) REFERENCES Bank (BankID) ON DELETE CASCADE,
	FOREIGN KEY (UserID) REFERENCES User (ID) ON DELETE CASCADE,
	FOREIGN KEY (LendID) REFERENCES Lend (ID) ON DELETE CASCADE
);

CREATE TABLE Credit (
	CreditID VARCHAR(255) NOT NULL UNIQUE,
	BankID VARCHAR(255) NOT NULL,
	Amount INT NOT NULL,
	Notes TEXT,
	PRIMARY KEY (CreditID),
	FOREIGN KEY (BankID) REFERENCES Bank(BankID) ON DELETE CASCADE
);