version: '3.7'
services:
  app:
    build: ./web_app
    ports:
      - 3000:3000
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - MysqlServer=mysqldb
      - DB_PORT=3306
      - MysqlDatabase=${MYSQL_DATABASE}
      - MysqlUser=${MYSQL_USER}
      - MysqlPassword=${MYSQL_PASSWORD}
      - APP_ENV=${APP_ENV}
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - CALLBACKURL=${CALLBACKURL}
      - USER_EMAIL=${USER_EMAIL}
    restart: unless-stopped
    networks:
      - nodejs-mysql-network
  mysqldb:
    image: mysql:8.0.33
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./behisebe_alpha.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data: 
networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network